#my.profile: @my.profile@

spring:
  application:
    name: expenses-ms
  config:
#    activate:
#      on-profile: dev
    import:
      configserver:
  cloud:
    config:
      fail-fast: true
      uri: http://localhost:8888

#server:
#  port: 8002
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/myFinance
#    username: root
#    password: 12345
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#  devtools:
#    restart:
#      enabled: true