address:
  service:
    balance-ms: http://127.0.0.1:8003
    expenses-ms: http://127.0.0.1:8002
    revenues-ms: http://127.0.0.1:8001

server:
  port: 8010

spring:
  thymeleaf:
    cache: false
    check-template-location: true

  devtools:
    restart:
      enabled: true
      additional-paths:
        - file:src/main/resources/templates/
        - file:src/main/resources/static/

